### ISSUE TITLE
Handle `wheel` package warning when building the Docker image

### ISSUE THREAD

**Issue by diegovalenzuelaiturra** [TeselaGen/api-client#5]
Currently, when excecuting this line of the `Dockerfile`

https://github.com/TeselaGen/api-client/blob/a3dec6db82308deb3bc0070018bbacb9db0c8f2f/docker_environment/Dockerfile#L81-L82

The following warning raises :

```diff
- WARNING: The wheel package is not available.
```

It should probably be fixed by adding the package, probably with a fixed version, e.g.`wheel==0.36.2` to `requirements.txt` or by adding a docker command before installing the library, containing the following instruction

```Dockerfile
# Dockerfile, before installing the package
RUN python3 -m pip install wheel==0.36.2
```

This has been mentioned  in https://github.com/TeselaGen/api-client/pull/2#issuecomment-749664021

**Comment by AndresPerezTesela** [comment]
Dockerfile modified fixing this issue at: https://github.com/TeselaGen/api-client/pull/12
