### ISSUE TITLE
Make a Plan and overview issue to Implement CI milestone

### ISSUE THREAD

**Issue by juanneilson** [TeselaGen/api-client#9]
Remember this issue also:

https://github.com/TeselaGen/ai/issues/268

**Comment by juanneilson** [comment]
- [x] **Set a Continuous Integration Automation milestone** :
    * Evaluate transitioning to Docker Compose, for example, and/or through the use of GitHub actions, etc. to automate, separate and simplify tasks.
    * As a starting point (MVP) we can consider the API Client repository, because it is directly related to quality of our customer service, and also the complexity of the package is still low.
    * Some of the immediately available actions for this repository are [here](https://github.com/TeselaGen/api-client/actions/new)

**Comment by diegovalenzuelaiturra** [comment]
Closing this issue, since the pipeline will be similar to the ones used internally, which is being managed by the team in another project.

- https://github.com/TeselaGen/ds-python-lib/issues/161

- GitHub actions are not considered in this pipeline.
